### PR TITLE
New Streams implementation

### PR DESCRIPTION
**Pull request by cstamas**
Hi Julien,

I moved the sources into lzma-java project to lessen deps and make it move faster and leave it "self contained".

I kept the packages (as org.cservenak.streams) since they are really generic and putting them under "lzma..." seemed not so smart move to me. You can freely reshuffle if you want.

Also, I kept old (your?) stream implementations, but they still has some threading problem, I did not investigate further. The new streams work like charm. ;)

### CODE REVIEW

**Comment by jponge** [comment]
This looks very good. I'm going to handle it shortly, and probably release straight afterwards ;-)

**Comment by jponge** [comment]
Your tests do not pass :-)

Any idea?

```
-------------------------------------------------------------------------------
Test set: lzma.streams.RoundtripTest
-------------------------------------------------------------------------------
Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 8.539 sec <<< FAILURE!
testStreamingEncoderDecoder(lzma.streams.RoundtripTest)  Time elapsed: 0.64 sec  <<< FAILURE!
junit.framework.AssertionFailedError: Source and uncompressed content does not equals!
    at junit.framework.Assert.fail(Assert.java:47)
    at junit.framework.Assert.assertTrue(Assert.java:20)
    at lzma.streams.RoundtripTest.performStreamRoundtrip(RoundtripTest.java:140)
    at lzma.streams.RoundtripTest.testStreamingEncoderDecoder(RoundtripTest.java:42)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at junit.framework.TestCase.runTest(TestCase.java:168)
    at junit.framework.TestCase.runBare(TestCase.java:134)
    at junit.framework.TestResult$1.protect(TestResult.java:110)
    at junit.framework.TestResult.runProtected(TestResult.java:128)
    at junit.framework.TestResult.run(TestResult.java:113)
    at junit.framework.TestCase.run(TestCase.java:124)
    at junit.framework.TestSuite.runTest(TestSuite.java:232)
    at junit.framework.TestSuite.run(TestSuite.java:227)
    at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
    at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:35)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:146)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:97)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.apache.maven.surefire.booter.ProviderFactory$ClassLoaderProxy.invoke(ProviderFactory.java:103)
    at $Proxy0.invoke(Unknown Source)
    at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:145)
    at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcess(SurefireStarter.java:87)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:69)
```

**Comment by jponge** [comment]
I tried with Maven3 and it's even worse: the test is in a deadlock on the roundtrip test. Your streams do not seem to be free of concurrency issues!

**Comment by cstamas** [comment]
That's testing your streams :)

"My" (the new) streams are tested in method performAltStreamRoundtrip() starting on line 144.

And since old streams has that threading problem, sometimes they pass, sometimes not. Frankly, I'd just remove the test for old streams and the old stream implementations ;)

**Comment by cstamas** [comment]
Yes, I forgot to tell, that I "merged" your old testing code into this one single new test class. So it performs "low" level tests against Encoder/Decoder, against "old" streams and against "new" streams.

**Comment by cstamas** [comment]
Just to clear up:

If you take a peek here:
https://github.com/cstamas/lzma-java/tree/master/src/main/java/lzma/streams

The LzmaInputStream and LzmaOutputStream are left in there untouched, I call them "old" streams and I already pointed out threading problems in them.

The LzmaDecompressingInputStream and LzmaCompressingOutputStream are the new ones.

And the single UT class tests them all, and it does fail (and deadlocks sometimes) on tests involving LzmaInputStream/LzmaOutputStream

**Comment by jponge** [comment]
Oh I see...

I will check again and if I'm ok with your new streams I will replace the "old" ones with the "new" ones. I'd rather preserve API compatibility if possible, so I may do a few refactorings.

Cheers

**Comment by cstamas** [comment]
Sure, that's what I implied with "You can freely reshuffle if you want" in initial pull request description.

Removing old classes and putting the new ones in their place would be the best, but I did not want to do that blindly, I left that for you ;)

**Pull request merged**
